"""empty message

Revision ID: a2f03985e8d1
Revises: 20bc2a9395d5
Create Date: 2025-09-29 20:36:32.844275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2f03985e8d1"
down_revision: Union[str, Sequence[str], None] = "20bc2a9395d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password_hash", sa.String(), nullable=False))
    op.add_column("users", sa.Column("news_filters", sa.JSON(), nullable=False))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "news_filters")
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
